version: "3.4"

volumes:
  playlist-manager-data:

services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: PlaylistManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./script:/app-scripts:ro
      - playlist-manager-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"