version: "3.4"

volumes:
  cqrs-data:

services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: CQRSMediatR
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./script:/app-scripts:ro
      - cqrs-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"